#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/capstone
spring.datasource.url=jdbc:mysql://mysql-db:3306/capstone
spring.datasource.username=root
spring.datasource.password=Root@23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework=INFO
logging.level.com.example.userservice=DEBUG
##eureka

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
#eureka.instance.instance-id=localhost:${server.port}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Enable all actuator endpoints
management.endpoints.web.exposure.include=*

# Show full health details
management.endpoint.health.show-details=always

# Enable tracing
management.tracing.enabled=true

management.tracing.sampling.probability=1.0

#spring.zipkin.base-url=http://localhost:9411/api/v2/spans
#management.observations.enable.http.server.requests=true
#management.observations.enable.http.client.requests=true
management.otlp.metrics.export.enabled=false
